name: bloc_infinity_list
description: "Infinite scrolling ListView with BLoC integration for Flutter applications."
version: 0.0.1
homepage: "https://github.com/FrenkyDema/bloc_infinity_list"

environment:
  sdk: '>=3.4.1 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8
  equatable: ^2.0.5
  flutter_bloc: ^8.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  plugin:
    platforms:
      android:
        package: francescodema.dev.bloc_infinity_list
        pluginClass: BlocInfinityListPlugin
      ios:
        pluginClass: BlocInfinityListPlugin
      linux:
        pluginClass: BlocInfinityListPlugin
      macos:
        pluginClass: BlocInfinityListPlugin
      windows:
        pluginClass: BlocInfinityListPluginCApi